global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using TTUWebLinkAppUnoApp.DataContracts;
global using TTUWebLinkAppUnoApp.DataContracts.Serialization;
global using TTUWebLinkAppUnoApp.Models;
global using TTUWebLinkAppUnoApp.Presentation;
global using TTUWebLinkAppUnoApp.Services.Caching;
global using TTUWebLinkAppUnoApp.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
